// Code generated by goctl. DO NOT EDIT.
package types

type Request struct {
	Id int `json:"userId" form:"userId"`
}

type Response struct {
	Code    int         `json:"code"`
	Message string      `json:"message"`
	Data    interface{} `json:"data"`
}
